export const FILTER_POKEMON = 'FILTER_POKEMON';
export const FETCH_POKEMON = 'FETCH_POKEMON';
export const SUBMIT_POKEMON = 'SUBMIT_POKEMON';
export const FETCH_MY_POKEMON = 'FETCH_MY_POKEMON';
export const FETCH_ONE_POKEMON = 'FETCH_ONE_POKEMON';
export const CREATE_TYPES = 'CREATE_TYPES';
export const UPDATE_SIDE_NAV = 'UPDATE_SIDE_NAV';
